apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-robotomediafiles
  namespace: roboto
  labels:
    app: roboto
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/disk1/mediafiles
    server: 192.168.10.6
    readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-robotomediafiles-claim
  namespace: roboto
  labels:
    app: roboto
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-robotopostgres
  namespace: roboto
  labels:
    app: roboto-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/disk1/robotoDB
    server: 192.168.10.6
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-robotopostgres-claim
  namespace: roboto
  labels:
    app: roboto-postgres
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-robototest
  namespace: roboto
  labels:
    app: roboto-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/disk1/robotoTest
    server: 192.168.10.6
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-robototest-claim
  namespace: roboto
  labels:
    app: roboto-test
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
