apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-robotoaudiofiles
  namespace: discord-bot-py
  labels:
    app: roboto
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/disk1/robotoDB
    server: 192.168.10.6
    readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-robotoaudiofiles-claim
  namespace: discord-bot-py
  labels:
    app: roboto
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-robotopostgres
  namespace: discord-bot-py
  labels:
    app: roboto-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/disk1/audiofiles
    server: 192.168.10.6
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-robotopostgres-claim
  namespace: discord-bot-py
  labels:
    app: roboto-postgres
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
